### ISSUE TITLE
[Bug report] Wrong description while no symptom data of a day

### ISSUE THREAD

**Issue by dixonsiu** [MyDataTaiwan/mylog14#121]
1. It alawys display "To day"  
1. i18n Key (noSymptom) is displayed not the translated value  

![Image from iOS (4)](https://user-images.githubusercontent.com/29846750/81278624-e6cb6080-9090-11ea-9fea-bfdbe6a90ec5.png)

**Comment by wcchung** [comment]
I can reproduce this issue. 

1. In English, It shout be "Today" & "No Symptom".
2. In Japan, lacking the translation of "No Symptom"
3. In French, the display is broken.

**Comment by seanwu1105** [comment]
This is has been resolved with the commit d9728cd80f5ac27601f44a7825e5342069e0c0e6.

**Comment by scott-dt** [comment]
20200706 v0.11.0 ios fix verified

**Comment by scott-dt** [comment]
20200707 v0.11.2 ios & Android fix verified

**Comment by wcchung** [comment]
![Image from iOS (1)](https://user-images.githubusercontent.com/12252921/86727941-7cb64400-c05e-11ea-9b3e-8f28a14d0658.png)

Test in  v0.11.2 with cold symptoms. When user enter a record with no symptoms, the record still display 4 Data fields.

The issue is not fixed.

**Comment by wcchung** [comment]
Because the UX had changed in v0.11.2. All symptoms will be shown on the page. See https://github.com/MyDataTaiwan/mylog14/issues/242
The issue can't be verified now.
